### ISSUE TITLE
Fatal error in Submitting Quiz Score Total

### ISSUE THREAD

**Issue by BrandonShutter** [katzwebservices/Gravity-Forms-Infusionsoft#12]
When submitting a score using the Quiz Addon, I get the following error:

`Fatal error: Uncaught Failed to invoke method addToGroup in class com.infusionsoft.api.xmlrpc.XmlRpcContactService: tagId must be a valid id Attempted: 1 time(s). thrown in /srv/www/calton.dev/current/web/app/plugins/infusionsoft/Infusionsoft/App.php on line 99`

The moment I stop trying to send the 'Quiz Score Total' in the plugin field, I no longer have a fatal error.

**Comment by BrandonShutter** [comment]
What's interesting however, is that my custom field in IS is being updated with the correct score.  So it's giving me a fatal error for apparently no reason?  However, this is creating a white screen, rather than redirecting or showing a confirmation.

**Comment by BrandonShutter** [comment]
Fyi, this issue still exists.

**Comment by roachdesign** [comment]
Hit this today, any ideas?
